using System.Reflection;

using A2MahleApp.Application.DependencyInjection;
using A2MahleApp.Infrastructure.DependencyInjection;
using A2MahleApp.Application.Features.Export;
using A2MahleApp.Client.WinUI.Services;
using A2MahleApp.Client.Services;

using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

using Serilog;

namespace A2MahleApp.Client;

public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        ConfigureSerilog(builder);

        builder
            .UseMauiApp<App>()
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
            });

        ConfigureConfiguration(builder);

        builder.Services
            .AddApplication()
            .AddInfrastructure(builder.Configuration);

        builder.Services.Configure<ComunicationTestServiceModel>(
            builder.Configuration.GetSection("CommunicationTest"));

        builder.Services.AddMauiBlazorWebView();
        builder.Services.AddSingleton<UpdateService>();

#if WINDOWS
        builder.Services.AddSingleton<IPdfFileSaver, PdfFileSaver>();
#endif

#if DEBUG
        builder.Services.AddBlazorWebViewDeveloperTools();
#endif

        return builder.Build();
    }



    private static void ConfigureConfiguration(MauiAppBuilder builder)
    {
        Assembly assembly = Assembly.GetExecutingAssembly();

        // The assembly name contains hyphens, while the C# root namespace does not.
        // Resolve the embedded resource by suffix so startup does not depend on the
        // exact manifest resource name generated by MSBuild.
        string resourceName = assembly
            .GetManifestResourceNames()
            .FirstOrDefault(name => name.EndsWith(".appsettings.json", StringComparison.OrdinalIgnoreCase))
            ?? throw new InvalidOperationException("Embedded appsettings.json resource was not found.");

        using Stream stream = assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException(
                $"Embedded resource '{resourceName}' could not be opened.");

        IConfiguration configuration = new ConfigurationBuilder()
            .AddJsonStream(stream)
            .Build();

        builder.Configuration.AddConfiguration(configuration);
    }

    private static void ConfigureSerilog(MauiAppBuilder builder)
    {
        string logDirectory = ResolveLogDirectory();
        Directory.CreateDirectory(logDirectory);

        string logPath = Path.Combine(logDirectory, "log-.txt");

        Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Debug()
            .MinimumLevel.Override("Microsoft", Serilog.Events.LogEventLevel.Warning)
            .Enrich.FromLogContext()
            .WriteTo.File(
                path: logPath,
                rollingInterval: RollingInterval.Day,
                retainedFileCountLimit: 30,
                shared: true,
                outputTemplate:
                    "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {SourceContext} {Message:lj}{NewLine}{Exception}")
            .CreateLogger();

        builder.Logging.ClearProviders();
        builder.Logging.AddSerilog(Log.Logger, dispose: true);
    }

    private static string ResolveLogDirectory()
    {
        return Path.Combine(AppContext.BaseDirectory, "Logs");
    }
};
